---
abstract: 'Get and parse the Linux desktop files.'
author:
  - 'Daniel "Trizen" Șuteu <trizenx@gmail.com>'
build_requires: {}
configure_requires:
  Module::Build: '0'
dynamic_config: 1
generated_by: 'Module::Build version 0.422, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Linux-DesktopFiles
provides:
  Linux::DesktopFiles:
    file: lib/Linux/DesktopFiles.pm
    version: '0.12'
requires:
  GDBM_File: '0'
  perl: '5.014'
resources:
  license: http://dev.perl.org/licenses/
  repository: https://github.com/trizen/Linux-DesktopFiles
version: '0.12'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
